display:
  inverted: false
  maximalist: false
  feedurl: https://bitcoinmagazine.com/feed 
  vcom: -2.61
  coinnames: false 
ticker:
  currency: bitcoin, ethereum, cardano, chainlink, cosmos, solana,polymath
  exchange: default
  fiatcurrency: usd
  updatefrequency: 60
  sparklinedays: 1
  coinsperpage: 3
function: 
  mode: crypto,redditquotes, wordaday, newyorkercartoon, guardianheadlines, textfilequotes
  weight: 1, 0, 0, 0, 0, 0
